openapi: 3.0.3
info:
  title: Registration API - OpenAPI 3.0
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8150/api/registration
tags:
  - name: registration
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /api/registration:
    post:
      tags:
        - registration
      summary: register guest to event
      operationId: registration
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid 
        '404':
          description: not found